switch to bashing

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -36,19 +36,20 @@ jobs:
     - name: Lint with Black
       if: steps.get_files_to_lint.outputs.any_changed == 'true'
       run: |
-        black --check ${{ steps.get_files_to_lint.outputs.all_changed_files }}
+        chmod +x ci-checks.sh
+        ./ci-checks.sh ${{ steps.get_files_to_lint.outputs.all_changed_files }}
 
-      continue-on-error: true
+    #   continue-on-error: true
 
-    - name: Generate annotations
-      if: success() || failure()
-      run: |
-        for file in ${{ steps.get_files_to_lint.outputs.all_changed_files }}; do
-          errors=$(black --check "$file" | awk -F ":" '{print $3":"$4}')
-          IFS=$'\n' read -rd '' -a errors_array <<<"$errors"
-          for err in "${errors_array[@]}"; do
-            IFS=: read -r line col <<<"$err"
-            echo "::error file=${file},line=${line},col=${col}::Black formatting issue found in ${file}."
-          done
-        done
+    # - name: Generate annotations
+    #   if: success() || failure()
+    #   run: |
+    #     for file in ${{ steps.get_files_to_lint.outputs.all_changed_files }}; do
+    #       errors=$(black --check "$file" | awk -F ":" '{print $3":"$4}')
+    #       IFS=$'\n' read -rd '' -a errors_array <<<"$errors"
+    #       for err in "${errors_array[@]}"; do
+    #         IFS=: read -r line col <<<"$err"
+    #         echo "::error file=${file},line=${line},col=${col}::Black formatting issue found in ${file}."
+    #       done
+    #     done
 
